### ISSUE TITLE
Problems in Demo

### ISSUE THREAD

**Issue by Yexiaoxing** [conferency/find-my-reviewers#14]
1. NLTK requires to download some data before LDA can be applied. Including `corpora/brown` and `tokenizers/punkt`.
2. The data we used in demo is a simplified version, which will lead to some errors in sql

```
Traceback (most recent call last):
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/cProfile.py", line 109, in runcall
    return func(*args, **kw)
  File "/Users/xiaoxing/Projects/find-my-reviewers/app/api/results.py", line 98, in get_result
    reviewers = pdf_match(file_hash)
  File "/Users/xiaoxing/Projects/find-my-reviewers/app/api/results.py", line 236, in pdf_match
    result, matched_topics = match_by_lda(text, model)
  File "/Users/xiaoxing/Projects/find-my-reviewers/core/matching/lda.py", line 109, in match_by_lda
    return detailed_results(results[:top], model_name), matched_topics
  File "/Users/xiaoxing/Projects/find-my-reviewers/core/matching/lda.py", line 130, in detailed_results
    profile = author_.ix[author_id].to_dict()
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/pandas/core/indexing.py", line 87, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1032, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/pandas/core/indexing.py", line 102, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/pandas/core/generic.py", line 1779, in xs
    loc = self.index.get_loc(key)
  File "/Users/xiaoxing/anaconda3/envs/fmr-3/lib/python3.6/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
    
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
    
  File "pandas/src/hashtable_class_helper.pxi", line 404, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8564)
    
  File "pandas/src/hashtable_class_helper.pxi", line 410, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:8508)
    
KeyError: 11548
```

**Comment by alanzchen** [comment]
Yes, we do need to come up with a better demo database.

We'll come back to this once we finished our new approach.

**Comment by Yexiaoxing** [comment]
Problem 1 has been fixed in #15.
