### ISSUE TITLE
Cannot update pdf

### ISSUE THREAD

**Issue by alex1007** [conferency/find-my-reviewers#4]
```
127.0.0.1 - - [13/Aug/2017 17:13:49] "POST /api/upload-file HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/leonf/Develop/workspace/conferency/find-my-reviewers/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/leonf/Develop/workspace/conferency/find-my-reviewers/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/leonf/Develop/workspace/conferency/find-my-reviewers/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/leonf/Develop/workspace/conferency/find-my-reviewers/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/leonf/Develop/workspace/conferency/find-my-reviewers/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/leonf/Develop/workspace/conferency/find-my-reviewers/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/leonf/Develop/workspace/conferency/find-my-reviewers/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/leonf/Develop/workspace/conferency/find-my-reviewers/venv/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cProfile.py", line 149, in runcall
    return func(*args, **kw)
  File "/Users/leonf/Develop/workspace/conferency/find-my-reviewers/app/api/upload.py", line 24, in upload_file
    uploaded_file.save(full_path)
  File "/Users/leonf/Develop/workspace/conferency/find-my-reviewers/venv/lib/python2.7/site-packages/werkzeug/datastructures.py", line 2597, in save
    dst = open(dst, 'wb')
IOError: [Errno 2] No such file or directory: '...../find-my-reviewers/app/static/upload/papers/dunlosky.pdf'
```

**Comment by alex1007** [comment]
add folders: upload and paper

**Comment by harrywang** [comment]
Did you mean cannot upload papers?

**Comment by alanzchen** [comment]
I think the problem is that by default the application did not create the "upload" and "papers" folder.
